Mobile/TodoApp/urls.py
from django.urls import path
from . import views
app_name='phone'
urlpatterns = [
    path('',views.Home,name='home'),
    path('<slug:c_slug>/',views.Home,name='product_by_category'),
    path('details/<int:id>',views.Details,name='details'),

]

Mobile/Todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls')),
    path('auth/',include('userapp.urls')), 
    path('searchapp/',include('searchApp.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Mobile/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('addcart/<int:id>',views.addcart,name='addcart'),
    path('displaycart/',views.displaycart,name='displaycart'),    
    # path('delete/<int:id>',views.Delete,name='delete'),
    
    

]

Mobile/searchApp/urls.py
from django.urls import path
from . import views
app_name='searchapp'
urlpatterns = [
    path('search/',views.Search,name='search'),
    
]

Mobile/userapp/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.registerUser,name='register'),
    path('loginuser/',views.loginUser,name='loginuser'),
    path('logout/',views.loginUser,name='logout'),
]

Mobile/TodoApp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)
    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name
    def get_url(self):
        return reverse('phone:product_by_category',args=[self.slug])

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='product',blank=True)
    price=models.DecimalField(max_digits=8,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    class Meta:
        ordering=('name',)
        
        
    def __str__(self):
        return self.name

Mobile/cart/models.py
from django.db import models
from TodoApp.models import Product
# Create your models here.

class Cart(models.Model):
    user=models.CharField(max_length=200)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    
    class Meta:
        db_table='cart'
        
        

Mobile/searchApp/models.py
from django.db import models

# Create your models here.

Mobile/userapp/models.py
from django.db import models

# Create your models here.

Mobile/TodoApp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Product,Category
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def Home(request,c_slug=None,stock=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=Product.objects.all().filter(category=c_page,available=True)

    else:
        product_list=Product.objects.all().filter(available=True)
    
    paginator=Paginator(product_list,10)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except(EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
   
    return render(request,'index.html',{'data':product_list,'products':products,'category':c_page})



def Details(req,id):
    data=Product.objects.get(id=id)
    return render(req,'details.html',{'data':data})

Mobile/cart/views.py
from django.shortcuts import render,redirect
from TodoApp.models import Product
from.models import Cart
from  django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def addcart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    print(product)
    try:
        cart=Cart.objects.get(product=product)
        if cart.quantity<cart.product.stock:
            cart.quantity+=1
            cart.save()
            
        
        
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=product,quantity=1)
    return redirect('cart:displaycart')


def displaycart(req):
    user=req.session['user']
    cart=Cart.objects.all().filter(user=user)
    cart_items_count=Cart.objects.filter(user=req.user).count()

    return render(req,'cart.html',{'cart_items_count':cart_items_count,'cart':cart})



# def Delete(req,id):
#     cancel=Cart.objects.get(id=id)
#     if req.method=="POST":
#         Cart.objects.filter(id=id).delete()
#         return redirect('cart:displaycart')
#     return render(req,'delete.html',{'cancel':cancel})

Mobile/searchApp/views.py
from django.shortcuts import render
from TodoApp.models import Product
from django.db.models import Q

# Create your views here.
def Search(req):
    products=None
    query=None
    if 'q' in req.GET:
        query=req.GET.get('q')
        print(req.GET.get('q'))
        products=Product.objects.all().filter(Q(name__contains=query))
    return render(req,'searchproduct.html',{'query':query,'products':products})
        

Mobile/userapp/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth
# Create your views here.
def registerUser(req):
    if req.method=="POST":
        fname=req.POST.get("fname","")
        lname=req.POST.get("lname","")
        email=req.POST.get("email","")
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        cpassword=req.POST.get("cpassword","")
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(req,"username already exist")
                return redirect('auth:register')
            elif User.objects.filter(email=email).exists():
                messages.info(req,"email already exist")
                return redirect('auth:register')
            else:
                user=User.objects.create_user(first_name=fname,last_name=lname,email=email,username=username,password=password)
                user.save()
                return redirect('auth:loginuser')
        else:
            messages.info(req,"password not matched")
            return redirect('phone:home')
    
    return render(req,'registeruser.html')

def loginUser(req):
    if req.method=='POST':
        username=req.POST.get("username","")
        password=req.POST.get("password","")
        user=auth.authenticate(username=username,password=password)
        print(user)
        if user is not None:
            auth.login(req,user)
            print(type(user))
            req.session['user']=str(user)
            return redirect('phone:home')
        else:
            messages.info(req,'invalid usernamr or password')
    return render(req,'loginuser.html')


def logout(req):
    auth.logout(req)
    # del req.session['user']
    req.session.pop('user',None)
    return redirect('phone:home')   

Mobile/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
  
  </head>
  <body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

Mobile/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="row">
  <div class="col-lg-8">
    <h1 class="yr mt-3 mb-5">YOUR PURCHASE CHART</h1>
    <table class="tbl table w-100">
      <thead class="thead-light">
        <tr class="trr bg-secondary">
          <th scope="col" style="width: 350px;">
            <h3>product</h3>
          </th>
          <th scope="col">
            <h3>quantity</h3>
          </th>
          <th scope="col">
            <h3>price</h3>
          </th>
          <th scope="col">
            <h3>Cancel</h3>
          </th>
          <th scope="col">
            <h3>buy Now</h3>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          {% for cartitem in cart %}

          <th scope="row">
            <img class="crtimg me-3 shadow" src="{{cartitem.product.image.url}}" alt="">{{cartitem.product}}
          </th>
          <td>
            <h4 class="qt mt-4 ms-4 me-5 shadow"><button class="btn">-</button>{{cartitem.quantity}}<a href=""class="btn">+</button></h4>
          </td>
          <td>
            <h4 class="mt-4 shadow">{{cartitem.product.price}}</h4>
          </td>
          <td><a href="" class="btn btn-danger mt-4 shadow">Cancel</a></td>
          <td><button class="btn btn-success mt-4 shadow">Buy Now</button></td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
  <div class="prd col-lg-3">
    <table class="tble table">
    <thead class="thead-light">
      <tr class="trr bg-secondary">
        <th scope="col">
          <h3>price details</h3>
        </th>

      </tr>
    </thead>
    <tbody>
      <tr>

        <th class="rr" scope="row">
          <h4 class="mt-4 ms-4">TOTAL:$ </h4>
        </th>
      </tr>
    </tbody>
    </table>



  </div>
</div>
<a href="{% url 'phone:home' %}" class="purch btn btn-primary pt-2 pb-2 ps-2 pe-2">
  <h4>continue purchase</h4>
</a>


{% endblock %}

Mobile/templates/delete.html
{% comment %} {% extends 'base.html' %}
    {% block content %}
<div class="container">
    <div class="row">
        <div class="d-flex justisfy-content-center">
            <form action="" method="post" class="form w-50">
                {% csrf_token %}
                <div class="my-3">
                    <h1>DO YOU WANT TO CANCEL?</h1>
                </div>
                <div class="my-3 text-center mx-0">
                    <button class="btn btn-primary">CANCEL</button>
                </div>
            </form>
        </div>
    </div>
 </div>   
{% endblock %} {% endcomment %}

Mobile/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="conta container-fluid justify-content-center bg-light d-flex ">

    <div class="crd card rounded-2 bg-light mb-5" style="border:0;">
        <div class="row">
            <h1 class="hed2">{{data.name}}</h1>
            <div class="cd card shadow-lg bg-body rounded mb-4">
                <img src="{{data.image.url}}" class="card-img-top rounded-2 mt-4 ms-4" alt="...">
                <div class="card-body">

                </div>
            </div>
            <div class="col2 col-7">
                <h2>{{data.name}}</h2>
                <h5>{{data.desc}}</h5>
                <h3 class="pr" style="color: rgb(14, 155, 38);">INR {{data.price}}</h3>
                <h5 class="ca mt-3">category: {{data.category}}</h5>
                <h5>created date: {{data.created}}</h5>
                <h5 class="up mb-4">updated date: {{data.updated}}</h5>

                {% if data.stock >= 1 %}
                <a href="{% url 'cart:addcart' data.id %}"class="btn btn-warning me-3 p-3"><svg xmlns="http://www.w3.org/2000/svg" height="26" viewBox="0 -960 960 960" width="24"><path d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg>Add to cart </a> 
                <button class="btn btn-primary p-3">Buy Now</button>
                {% else %}
                <span>
                    <h3 class="out" style="color: red;">out of stock</h3>
                </span>
                {% endif %}

            </div>
        </div>
    </div>

</div>

{% endblock %}

Mobile/templates/footer.html
<nav class="navbar bg-dark navbar-dark">
    <div class="container-fluid p-0">
      <span class="navbar-brand mb-0 mx-auto h1">footer</span>
    </div>
  </nav>
  

Mobile/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if category %}
<div class="container-fluid mb-3">
  <h1 class="hed mt-3">{{category.name}}</h1>
  <img class="can rounded-5 " src="{% static './images/Screenshot from 2024-02-02 11-27-20.png' %}" style="margin-left: 280px;" width="68%" height="400" alt="">
</div>
{% else %}
<div class="container-fluid mb-3">
  <h1 class="hed mt-3 mb-2">All Products</h1>
  <img class="can rounded-5 " src="../static/images/canva.png" style="margin-left: 30px;" width="96%" height="600"
    alt="">
  <h5 class="des mt-4 mb-5">A mobile phone (or cellphone[a]) is a portable telephone that can make and receive calls
    over a radio frequency link while the user is moving within a telephone service area, as opposed to a fixed-location
    phone (landline phone). The radio frequency link establishes a connection to the switching systems of a mobile phone
    operator, which provides access to the public switched telephone network (PSTN). Modern mobile telephone services
    use a cellular network architecture and therefore mobile telephones are called cellphones (or "cell phones") in
    North America.</h5>
</div>
{% endif %}

<div class="container-fluid">
  <div class="card-group mb-3 d-flex justify-content-center">
    {% for i in products %}
    {% if i.available %}
    <a href="{% url 'phone:details' i.id %}">
      <div class="cad shadow me-4 p-3 mb-5">
        <img src="{{i.image.url}}" height="280px" class="card-img-top" alt="...">
        <div class="card-body">
          <h3 class="card-title mt-2">{{i.name}}</h3>
          <h5 class="card-text" style="color: rgb(44, 159, 44);">${{i.price}}</h5>
        </div>
      </div>
    </a>
    {% endif %}
    {% endfor %}
  </div>
  <div class="paginator mx-auto mb-2">
    {% if products.paginator.num_pages > 1 %}<hr>
      <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-secondary btn-sm {% if products.number == pg %}active {% endif %}">{{pg}}</a>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>


{% endblock %}

Mobile/templates/loginuser.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <form class="login mt-5 mb-2" method="post" action="" enctype="multipart/form-data" style="width: 380px;">
        {% csrf_token %}
        <h2 class="lhd">Login</h2>
        <input class="form-control mt-4 mb-3 type="text name="username" placeholder="username">

        <input class="form-control mb-2" type="textr" name="password" placeholder="password">
        <button class="btn btn-success mt-3 mb-2" style="margin-left: 150px;">submit</button>
    </form>
</div>



{% endblock %}

Mobile/templates/nav.html
{% load static %}
<nav class="navbar bg-dark navbar-dark">
  <div class="container-fluid p-0">
    <span class="navbar-brand mb-0 mx-auto h1"></span>
      <form class="d-flex" role="search" action="{% url 'searchapp:search' %}" method="GET">
      <input class="bttn form-control" type="search" name="q" placeholder="Search" aria-label="Search">
      <button class="btn ser" type="submit"><img src="{% static './images/search_white_24dp.svg' %}" alt=""></button>
      </form>
      {% if user.is_authenticated %}           
      <span class="us me-3 mt-2" style="color: white;">{{user}}</span>
      <a href="{% url 'auth:logout' %}" class="btn btn-danger ps-3 pe-3 lgo " type="submit">logout</a>
      {% else %}
      <a href="{% url 'auth:register' %}" class=" btn btn-light ps-3 pe-3 me-3" type="submit">sign in</a>
      <a href="{% url 'auth:loginuser' %}" class="btn btn-light ps-3 pe-3 me-3" type="submit">login</a>
      {% endif %}
  </div>
</nav>


<nav class="navbar navbar-expand-lg nvbk">  
  <div class="container-fluid nv">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="ct navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active mt-1" aria-current="page" href="{% url 'phone:home' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mt-1" style="margin-right: 885px;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'phone:home' %}">All products</a></li>
            {% for link in links %}
            <li><a class="dropdown-item" href="{{link.get_url}}">{{link.name}}</a></li>
            {% endfor %} 
          </ul>
   
        </li>
        {% if cart_items_count > 0 %}
        <a href="{% url 'cart:displaycart' %}" class="catt btn btn-warning ps-4 pe-4 pt-2 pb-2"><svg xmlns="http://www.w3.org/2000/svg" height="30" viewBox="0 -960 960 960" width="30"><path d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg>cart<span class="badge badge-light">{{cart_items_count}}</span></a>
        {% else %}
        <a href="{% url 'cart:displaycart' %}"></a>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

Mobile/templates/registeruser.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" class="bg-light p-3 mt-5 mb-5 rounded sing" style="width: 450px;">
    {% csrf_token %}
    <h2 class="signup text-center">SIGN UP</h2>
    <div class="mb-3">
        <label for="fname" class="form-label">First Name</label>
        <input type="text" class="form-control" id="fname" placeholder="First Name" name="fname">
    </div>
    <div class="mb-3">
        <label for="lname" class="form-label">Last Name</label>
        <input type="text" class="form-control" id="lname" placeholder="Last Name" name="lname">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" placeholder="Email" name="email">
    </div>
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" placeholder="Username" name="username">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" placeholder="Password" name="password">
    </div>
    <div class="mb-3">
        <label for="cpassword" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="cpassword" placeholder="Confirm Password" name="cpassword">
    </div>
    <div>
        <button type="submit" class="btn btn-success" style="margin-left: 160px;">Submit</button>
    </div>
</form>

{% endblock %}

Mobile/templates/searchproduct.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid mb-3">
  <h1 class="hed mt-3">{{category.name}}</h1>
  <img class="can rounded-5 " src="{% static './images/Screenshot from 2024-02-02 11-27-20.png' %}" style="margin-left: 280px;" width="68%" height="400" alt="">
</div>
<div class="prcnt container-fluid d-flex justify-content-center">
  <div class="card-group mb-3">
    {% for product in products %}
    <a href="{% url 'phone:details' product.id %}">
      <div class="cad shadow me-4 p-3 mb-5 mt-3">
        <img src="{{product.image.url}}" height="250px" class="card-img-top" alt="...">
        <div class="card-body">
          <h3 class="card-title mt-2">{{product.name}}</h3>
          <h5 class="card-text" style="color: rgb(44, 159, 44);">${{product.price}}</h5>
        </div>
      </div>
    </a>
    {% empty %}
    <h3 class="NT">product Not found!</h3>
    {% endfor %}

  </div>
</div>


{% endblock %}